# Generated by Django 5.2.6 on 2025-09-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_hobby_img_path_portfolioitem_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
