# Generated by Django 5.2.6 on 2025-09-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
